"""Pure artifact identity types shared across every Reef layer.

These are plain value types with no storage behavior: :class:`ArtifactRef`
names one artifact version, :class:`LiveWeightArtifactRef` narrows it to a
live serving-engine weight update, and :class:`WeightVersionSpan` records
which such serving identity produced each response-token range. Their wire
helpers remain pure. Storage-backed behavior (materialization, repositories)
lives in ``reef.artifact``, which builds on these identities.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class ArtifactRef:
    """Immutable identity for one artifact version."""

    artifact_id: str
    version: str
    parent_version: str | None


@dataclass(frozen=True)
class LiveWeightArtifactRef(ArtifactRef):
    """A live weight version bound to one serving-engine update.

    Slime tokens combine a training-group incarnation with a monotonic update
    sequence, so a restarted group cannot reuse an old token for different
    weights. The token identifies engine state; it does not make the
    underlying bytes durable.
    """

    weight_version: str

    def __post_init__(self) -> None:
        if not isinstance(self.weight_version, str) or not self.weight_version:
            raise ValueError("weight_version must be a non-empty string")


@dataclass(frozen=True)
class WeightVersionSpan:
    """Half-open response-token range generated by one serving version."""

    start: int
    end: int
    weight_version: str


def parse_weight_version_spans(
    value: Any,
    *,
    field_name: str = "weight_version_spans",
    response_length: int | None = None,
) -> tuple[WeightVersionSpan, ...]:
    """Return structurally valid contiguous half-open token spans.

    ``response_length`` makes coverage exact. Policies governing which
    serving-version transitions are acceptable belong to the caller.
    """
    if not isinstance(value, Sequence) or isinstance(value, str | bytes):
        raise ValueError(f"{field_name} must be a sequence")

    spans: list[WeightVersionSpan] = []
    cursor = 0
    for index, raw in enumerate(value):
        if not isinstance(raw, Mapping):
            raise ValueError(f"{field_name}[{index}] must be an object")
        try:
            start = raw["start"]
            end = raw["end"]
            version = raw["weight_version"]
        except KeyError as exc:
            raise ValueError(f"invalid {field_name}[{index}]") from exc
        if (
            not isinstance(start, int)
            or isinstance(start, bool)
            or start != cursor
            or not isinstance(end, int)
            or isinstance(end, bool)
            or end <= start
            or not isinstance(version, str)
            or not version
        ):
            raise ValueError(f"invalid {field_name}[{index}]")

        spans.append(WeightVersionSpan(start=start, end=end, weight_version=version))
        cursor = end

    if response_length is not None and cursor != response_length:
        raise ValueError(f"{field_name} cover {cursor} response tokens, expected {response_length}")
    return tuple(spans)


def encode_artifact_ref(ref: ArtifactRef) -> dict[str, Any]:
    """Encode a ref with an explicit discriminator for its concrete type."""
    value: dict[str, Any] = {
        "kind": "weight" if isinstance(ref, LiveWeightArtifactRef) else "artifact",
        "artifact_id": ref.artifact_id,
        "version": ref.version,
        "parent_version": ref.parent_version,
    }
    if isinstance(ref, LiveWeightArtifactRef):
        value["weight_version"] = ref.weight_version
    return value


def decode_artifact_ref(value: Mapping[str, Any]) -> ArtifactRef:
    """Decode the current ref wire format without legacy-format inference."""
    kind = value.get("kind")
    artifact_id = value.get("artifact_id")
    version = value.get("version")
    parent_version = value.get("parent_version")
    if kind not in ("artifact", "weight"):
        raise ValueError("artifact ref kind must be 'artifact' or 'weight'")
    if not isinstance(artifact_id, str) or not artifact_id:
        raise ValueError("artifact ref requires artifact_id")
    if not isinstance(version, str) or not version:
        raise ValueError("artifact ref requires version")
    if parent_version is not None and not isinstance(parent_version, str):
        raise ValueError("artifact ref parent_version must be a string or null")
    if kind == "artifact":
        if "weight_version" in value:
            raise ValueError("artifact ref must not carry weight_version")
        return ArtifactRef(
            artifact_id=artifact_id,
            version=version,
            parent_version=parent_version,
        )
    weight_version = value.get("weight_version")
    if not isinstance(weight_version, str) or not weight_version:
        raise ValueError("weight artifact ref requires a non-empty weight_version")
    return LiveWeightArtifactRef(
        artifact_id=artifact_id,
        version=version,
        parent_version=parent_version,
        weight_version=weight_version,
    )


__all__ = [
    "ArtifactRef",
    "LiveWeightArtifactRef",
    "WeightVersionSpan",
    "decode_artifact_ref",
    "encode_artifact_ref",
    "parse_weight_version_spans",
]
