"""Render recorded episode traces as an offline, self-contained HTML viewer."""

from __future__ import annotations

import base64
import hashlib
import json
from pathlib import Path

if __package__:
    from .report import JsonValue, read_object
else:
    from report import JsonValue, read_object

HTML = """<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="__CSP__"><title>AgentCL recorded traces</title><style>
body{font:16px system-ui;margin:0;background:#f6f8fa;color:#18222d}header,main{max-width:1100px;margin:auto;padding:20px}
.controls{display:flex;flex-wrap:wrap;gap:10px}input,select,button{padding:10px;max-width:100%;font:inherit}
article{background:white;border:1px solid #ccd3da;padding:18px;border-radius:8px;margin-top:15px;overflow-wrap:anywhere}
pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f1f4f7;padding:12px}label{display:flex;flex-direction:column}
.badge{font-weight:bold}details{margin:12px 0}#status{padding:12px 0}@media(max-width:600px){header,main{padding:12px}.controls>*{width:100%}}
</style><header><h1>AgentCL recorded traces</h1><p>Student actions and tool observations are recorded data. Privileged training context is never student input. Teacher completions are not generated by this viewer.</p>
<div class="controls"><label>Search<input id="search" placeholder="Task, receipt or text"></label><label>Phase<select id="phase"><option value="">All phases</option></select></label><label>Task<select id="task"><option value="">All tasks</option></select></label><label>Attempt<select id="attempt"><option value="">All attempts</option></select></label><button id="download">Download filtered JSON</button><button id="reset">Reset filters</button></div><div id="status" role="status"></div></header><main id="results"></main>
<script id="records" type="application/json">__RECORDS__</script><script>
'use strict';const records=JSON.parse(document.getElementById('records').textContent);const controls=['search','phase','task','attempt'];
const field=id=>document.getElementById(id);const taskName=r=>r.category+'/'+r.task_id;
for(const [id,values] of [['phase',records.map(r=>r.phase)],['task',records.map(taskName)],['attempt',records.map(r=>String(r.attempt))]]){
for(const value of [...new Set(values)].sort()){const o=document.createElement('option');o.value=value;o.textContent=value;field(id).append(o)}}
let selected=[];function block(parent,title,value){const d=document.createElement('details');const s=document.createElement('summary');s.textContent=title;d.append(s);const p=document.createElement('pre');p.textContent=typeof value==='string'?value:JSON.stringify(value,null,2);d.append(p);parent.append(d)}
function render(){const search=field('search').value.toLowerCase();selected=records.filter(r=>(!field('phase').value||r.phase===field('phase').value)&&(!field('task').value||taskName(r)===field('task').value)&&(!field('attempt').value||String(r.attempt)===field('attempt').value)&&JSON.stringify(r).toLowerCase().includes(search));field('results').replaceChildren();field('status').textContent=selected.length+' matching episodes';field('download').disabled=!selected.length;if(!selected.length){field('results').textContent='No episodes match. Export recorded episodes or change filters.';return}
for(const r of selected){const a=document.createElement('article');const h=document.createElement('h2');h.textContent=taskName(r)+' · '+r.phase+' · attempt '+r.attempt;a.append(h);const b=document.createElement('p');b.className='badge';b.textContent='Outcome: '+r.outcome+' | score: '+r.score+' | release: '+r.release_id;a.append(b);block(a,'Metadata',{episode_id:r.episode_id,references:r.references,runtime_load_id:r.runtime_load_id,elapsed_seconds:r.elapsed_seconds,prompt_tokens:r.prompt_tokens,completion_tokens:r.completion_tokens,fault:r.fault});block(a,'Exact student requests, responses and tool observations',r.turns);block(a,'Recorded trajectory',r.trajectory);block(a,'Privileged training context / feedback (not student-visible)',r.terminal_report||'No training report; evaluation has no teacher context');block(a,'Exact privileged teacher prompt/tokens',r.teacher_record||'Unavailable: native training records have not been attached; do not treat context alone as the exact rendered teacher prompt');field('results').append(a)}}
field('reset').addEventListener('click',()=>{for(const id of controls)field(id).value='';render()});for(const id of controls)field(id).addEventListener(id==='search'?'input':'change',render);field('download').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(selected,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='agentcl-traces.json';link.click();URL.revokeObjectURL(url)});render();
</script></html>"""


def browser_json(value: JsonValue) -> JsonValue:
    """Preserve large metadata integers as decimal strings in browser downloads."""
    if isinstance(value, int) and not isinstance(value, bool) and abs(value) > 2**53 - 1:
        return str(value)
    if isinstance(value, dict):
        return {key: browser_json(item) for key, item in value.items()}
    if isinstance(value, list):
        return [browser_json(item) for item in value]
    return value


def render_traces(run_root: Path) -> Path:
    records = []
    for path in sorted((run_root / "episodes").glob("*.json")):
        record = read_object(path)
        report_path = run_root / "reports" / f"{record['report_id']}.json"
        if report_path.exists():
            record["terminal_report"] = read_object(report_path)
        teacher_path = run_root / "teacher-records" / f"{record['report_id']}.json"
        if teacher_path.exists():
            record["teacher_record"] = read_object(teacher_path)
        records.append(record)
    phases = {
        phase: index
        for index, phase in enumerate(("baseline", "baseline-independent", "train", "frozen-repeat", "independent"))
    }
    records.sort(
        key=lambda row: (
            phases.get(str(row["phase"]), 99),
            int(row.get("campaign_position", row.get("position", 0))),
            int(row["attempt"]),
        )
    )
    encoded = (
        json.dumps(browser_json(records), ensure_ascii=True, allow_nan=False)
        .replace("<", "\\u003c")
        .replace("&", "\\u0026")
    )
    destination = run_root / "traces.html"
    document = HTML.replace("__RECORDS__", encoded)
    script = document.rsplit("<script>", 1)[1].split("</script>", 1)[0]
    script_hash = base64.b64encode(hashlib.sha256(script.encode()).digest()).decode()
    policy = (
        "default-src 'none'; script-src 'sha256-"
        + script_hash
        + "'; style-src 'unsafe-inline'; connect-src 'none'; base-uri 'none'; form-action 'none'"
    )
    destination.write_text(document.replace("__CSP__", policy))
    return destination
